# Generated by Django 3.2.25 on 2024-04-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_historicalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprice',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalprice',
            name='total_volume',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
