# Generated by Django 3.2.25 on 2024-04-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20240414_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=5, max_digits=25, null=True)),
                ('volume_24h', models.DecimalField(decimal_places=5, max_digits=25, null=True)),
                ('change_24h', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
