# Generated by Django 3.2.25 on 2024-04-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_auto_20240427_0201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitcoinLive',
        ),
        migrations.DeleteModel(
            name='Cryptocurrency',
        ),
        migrations.DeleteModel(
            name='HistoricalData',
        ),
        migrations.AddField(
            model_name='historicalprice',
            name='symbol',
            field=models.CharField(default='BTC', max_length=10),
        ),
    ]
