# Generated by Django 3.2.25 on 2024-04-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0012_auto_20240428_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprice',
            name='granularity',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('5min', 'Five Minutes')], default='hourly', max_length=10),
        ),
    ]
