# Generated by Django 3.2.25 on 2024-05-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0013_historicalprice_granularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
