# Generated by Django 3.2.25 on 2024-05-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0014_cryptocurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
