# Generated by Django 3.2.25 on 2024-05-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0015_alter_cryptocurrency_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='name',
            new_name='symbol_name',
        ),
    ]
