# Generated by Django 3.2.25 on 2024-04-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_holdings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=10000000.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profit_loss',
            field=models.FloatField(default=0.0),
        ),
    ]
