# Generated by Django 3.2.25 on 2024-05-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_amount_trade_amount_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='amount_usd',
            new_name='amount',
        ),
    ]
