# Generated by Django 3.2.25 on 2024-05-12 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_savedstrategy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedstrategy',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='savedstrategy',
            unique_together={('user', 'name')},
        ),
    ]
